on:
  push:
    
jobs:
  track_subfolder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: List Changed Files in Subfolder
        run: |
          git diff --name-only ${{ github.sha.before }} ${{ github.sha }} -- modules/archetypes/lib > changed_files.txt
          cat changed_files.txt
